cc_binary(
    name = "example",
    srcs = ["example.cc"],
    # TODO(malkia): This does not yet work.
    data = ["test.csv"],
    deps = [
        "//cpp/src/arrow",
        "//cpp/src/arrow/csv",
    ],
)
