package(
    default_visibility = ["//visibility:public"],
)

exports_files(
    [
        "azure.BUILD",
        "thrift.BUILD",
        "version.bzl",
        "deps.bzl",
        "wil.BUILD",
        "xsimd.BUILD",
    ],
)
