package(default_visibility = ["//visibility:public"])

exports_files(
    [
        "azure.BUILD",
        "thrift.BUILD",
        "version.bzl",
        "deps1.bzl",
        "deps2.bzl",
        "wil.BUILD",
        "xsimd.BUILD",
    ],
)
