package(
    default_visibility = ["//visibility:public"],
)

cc_library(
    name = "api",
    hdrs = [
        "io.h",
        "reader.h",
        "schema.h",
        "writer.h",
    ],
    include_prefix = "parquet/api",
    deps = [
        "//cpp/src/parquet",
    ]
)
