[cc_binary(
    name = name,
    srcs = [name + ".cc"],
    deps = ["//cpp/src/arrow"],
) for name in [
    "arrow_example",
    "compute_example",
    "dataset_example",
    "file_access_example",
]]
